import {
  AdminUser,
  MarketplaceUser,
  VerificationRequest,
  EscrowDispute,
  CmsLegalDoc,
  CmsFaqItem,
  CmsBrandAssets,
  MarketplaceTransaction,
  MarketplacePackage,
  MarketplaceOrder,
  SupportTicket,
} from '@/types/admin.types';

export const INITIAL_ADMIN_USER: AdminUser = {
  id: 'ADM-001',
  name: 'Sazzad Hoshen',
  email: 'sazzad.uiuxdesign@gmail.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  role: 'super_admin',
  status: 'active',
  twoFactorEnabled: true,
  lastLogin: 'Today at 09:15 AM',
  createdAt: '2025-01-10',
};

export const INITIAL_ADMIN_TEAM: AdminUser[] = [
  INITIAL_ADMIN_USER,
  {
    id: 'ADM-002',
    name: 'Camille Laurent',
    email: 'camille@influverse.com',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    role: 'admin',
    status: 'active',
    twoFactorEnabled: true,
    lastLogin: 'Yesterday at 04:30 PM',
    createdAt: '2025-03-12',
  },
  {
    id: 'ADM-003',
    name: 'Julian Vance',
    email: 'julian.finance@influverse.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    role: 'admin',
    status: 'active',
    twoFactorEnabled: true,
    lastLogin: '2 days ago',
    createdAt: '2025-04-05',
  },
  {
    id: 'ADM-004',
    name: 'Amara Diallo',
    email: 'amara.mod@influverse.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    role: 'admin',
    status: 'active',
    twoFactorEnabled: false,
    lastLogin: '3 hours ago',
    createdAt: '2025-06-18',
  },
];

export const INITIAL_USERS: MarketplaceUser[] = [
  {
    id: 'USR-8910',
    name: 'Sophie Kim',
    email: 'sophie@sophiekim.com',
    handle: 'sophiekim',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    role: 'creator',
    status: 'active',
    category: 'Beauty & Skincare',
    location: 'Los Angeles, CA',
    rating: 4.98,
    totalVolumeEur: 28400,
    ordersCount: 32,
    joinedDate: '2025-02-14',
  },
  {
    id: 'USR-8911',
    name: 'Maya Chen',
    email: 'maya@wellnesschen.com',
    handle: 'mayachen',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    role: 'creator',
    status: 'active',
    category: 'Fitness & Health',
    location: 'London, UK',
    rating: 5.0,
    totalVolumeEur: 19500,
    ordersCount: 24,
    joinedDate: '2025-03-01',
  },
  {
    id: 'USR-8912',
    name: 'Liam Carter',
    email: 'liam@cartercinematics.com',
    handle: 'liamcarter',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    role: 'creator',
    status: 'active',
    category: 'Tech & Gadgets',
    location: 'Berlin, Germany',
    rating: 4.92,
    totalVolumeEur: 42100,
    ordersCount: 41,
    joinedDate: '2025-01-20',
  },
  {
    id: 'USR-8913',
    name: 'Elena Rostova',
    email: 'elena@aura-cosmetics.com',
    handle: 'auracosmetics',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    role: 'brand',
    status: 'active',
    companyName: 'Aura Skincare Paris S.A.S.',
    location: 'Paris, France',
    totalVolumeEur: 68450,
    ordersCount: 18,
    joinedDate: '2025-01-15',
  },
  {
    id: 'USR-8914',
    name: 'Nordica Apparel',
    email: 'marketing@nordica-sports.se',
    handle: 'nordicasports',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    role: 'brand',
    status: 'active',
    companyName: 'Nordica Activewear AB',
    location: 'Stockholm, Sweden',
    totalVolumeEur: 34200,
    ordersCount: 11,
    joinedDate: '2025-04-10',
  },
  {
    id: 'USR-8915',
    name: 'Darius Vance',
    email: 'darius@vancehype.io',
    handle: 'dariusvance',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    role: 'creator',
    status: 'suspended',
    category: 'Crypto & Gaming',
    location: 'Miami, USA',
    rating: 3.4,
    totalVolumeEur: 4200,
    ordersCount: 5,
    joinedDate: '2025-05-12',
    banReason: 'Attempted off-platform WhatsApp payment to circumvent 15% platform escrow fee.',
    banActionType: 'temporary',
  },
  {
    id: 'USR-8916',
    name: 'Aria Montclaire',
    email: 'aria@montclaire.studio',
    handle: 'ariamontclaire',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    role: 'creator',
    status: 'active',
    category: 'Luxury Fashion',
    location: 'Milan, Italy',
    rating: 4.95,
    totalVolumeEur: 51200,
    ordersCount: 39,
    joinedDate: '2025-05-18',
  },
  {
    id: 'USR-8917',
    name: 'Kaito Tanaka',
    email: 'kaito@tanakagaming.jp',
    handle: 'kaitotanaka',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    role: 'creator',
    status: 'active',
    category: 'Gaming & Anime',
    location: 'Tokyo, Japan',
    rating: 4.88,
    totalVolumeEur: 31900,
    ordersCount: 29,
    joinedDate: '2025-04-22',
  },
  {
    id: 'USR-8918',
    name: 'Chronos Horology',
    email: 'partners@chronos-watches.ch',
    handle: 'chronoswatches',
    avatar: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=400&q=80',
    role: 'brand',
    status: 'active',
    companyName: 'Chronos Horology SA',
    location: 'Geneva, Switzerland',
    totalVolumeEur: 94500,
    ordersCount: 22,
    joinedDate: '2025-03-15',
  },
  {
    id: 'USR-8919',
    name: 'Chloe Dubois',
    email: 'chloe@epicureanlyon.fr',
    handle: 'chloedubois',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
    role: 'creator',
    status: 'active',
    category: 'Food & Culinary',
    location: 'Lyon, France',
    rating: 4.91,
    totalVolumeEur: 16800,
    ordersCount: 19,
    joinedDate: '2025-02-28',
  },
  {
    id: 'USR-8920',
    name: 'Apex Velocity',
    email: 'collabs@apexvelocity.com',
    handle: 'apexvelocity',
    avatar: 'https://images.unsplash.com/photo-1579389083078-4e7018379f7e?auto=format&fit=crop&w=400&q=80',
    role: 'brand',
    status: 'active',
    companyName: 'Apex Athletic Gear LLC',
    location: 'Austin, TX',
    totalVolumeEur: 82000,
    ordersCount: 31,
    joinedDate: '2025-01-05',
  },
  {
    id: 'USR-8921',
    name: 'Mateo Silva',
    email: 'mateo@silvavisuals.es',
    handle: 'mateosilva',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    role: 'creator',
    status: 'active',
    category: 'Travel & Cinematography',
    location: 'Barcelona, Spain',
    rating: 4.97,
    totalVolumeEur: 38600,
    ordersCount: 36,
    joinedDate: '2024-12-10',
  },
  {
    id: 'USR-8922',
    name: 'Lumina Smart Home',
    email: 'influencers@luminasmart.io',
    handle: 'luminahome',
    avatar: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=400&q=80',
    role: 'brand',
    status: 'active',
    companyName: 'Lumina Connected Tech Inc.',
    location: 'San Francisco, CA',
    totalVolumeEur: 54100,
    ordersCount: 16,
    joinedDate: '2024-11-20',
  },
  {
    id: 'USR-8923',
    name: 'Sarah Jenkins',
    email: 'sarah@jenkinsfamily.ca',
    handle: 'sarahjenkins',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    role: 'creator',
    status: 'active',
    category: 'Family & Lifestyle',
    location: 'Toronto, Canada',
    rating: 4.85,
    totalVolumeEur: 22300,
    ordersCount: 26,
    joinedDate: '2024-11-05',
  },
  {
    id: 'USR-8924',
    name: 'Botanica Organics',
    email: 'partnerships@botanica.ie',
    handle: 'botanicaorganics',
    avatar: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=400&q=80',
    role: 'brand',
    status: 'active',
    companyName: 'Botanica Organic Care Ltd',
    location: 'Dublin, Ireland',
    totalVolumeEur: 41700,
    ordersCount: 14,
    joinedDate: '2024-10-18',
  },
  {
    id: 'USR-8925',
    name: 'Alex Rivera',
    email: 'alex@riverasound.com',
    handle: 'alexrivera',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
    role: 'creator',
    status: 'active',
    category: 'Audio & Music Production',
    location: 'Nashville, TN',
    rating: 4.89,
    totalVolumeEur: 27500,
    ordersCount: 33,
    joinedDate: '2024-09-30',
  },
  {
    id: 'USR-8926',
    name: 'Zenith Security',
    email: 'marketing@zenithsecurity.com',
    handle: 'zenithsecurity',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=400&q=80',
    role: 'brand',
    status: 'active',
    companyName: 'Zenith Cyber Technologies',
    location: 'Tel Aviv, Israel',
    totalVolumeEur: 112000,
    ordersCount: 25,
    joinedDate: '2024-08-14',
  },
  {
    id: 'USR-8927',
    name: 'Fatima Al-Mansoor',
    email: 'fatima@almansoordesigns.ae',
    handle: 'fatimaalmansoor',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80',
    role: 'creator',
    status: 'active',
    category: 'Modest Luxury Fashion',
    location: 'Dubai, UAE',
    rating: 4.99,
    totalVolumeEur: 63400,
    ordersCount: 47,
    joinedDate: '2024-07-22',
  },
  {
    id: 'USR-8928',
    name: 'PureHops Craft',
    email: 'community@purehops.nl',
    handle: 'purehopscraft',
    avatar: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=400&q=80',
    role: 'brand',
    status: 'active',
    companyName: 'PureHops Brewing Co.',
    location: 'Amsterdam, Netherlands',
    totalVolumeEur: 18900,
    ordersCount: 8,
    joinedDate: '2024-06-11',
  },
  {
    id: 'USR-8929',
    name: 'Lucas Van Der Bilt',
    email: 'lucas@vanderbiltmotors.de',
    handle: 'lucasvanderbilt',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=400&q=80',
    role: 'creator',
    status: 'active',
    category: 'Automotive & Supercars',
    location: 'Munich, Germany',
    rating: 4.93,
    totalVolumeEur: 49800,
    ordersCount: 38,
    joinedDate: '2024-05-19',
  },
  {
    id: 'USR-8930',
    name: 'BoostNexus Network',
    email: 'admin@boostnexus-bots.ru',
    handle: 'boostnexus',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=400&q=80',
    role: 'creator',
    status: 'banned',
    category: 'Growth Hacks',
    location: 'Kyiv, Ukraine',
    rating: 2.1,
    totalVolumeEur: 1200,
    ordersCount: 2,
    joinedDate: '2024-04-02',
    banReason: 'Severe fraud: fabricated engagement and fraudulent follower botting.',
    banActionType: 'permanent',
  },
  {
    id: 'USR-8931',
    name: 'Veloce Cycles',
    email: 'team@velocecycles.it',
    handle: 'velocecycles',
    avatar: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=400&q=80',
    role: 'brand',
    status: 'active',
    companyName: 'Veloce Mobility SpA',
    location: 'Turin, Italy',
    totalVolumeEur: 29300,
    ordersCount: 10,
    joinedDate: '2024-03-14',
  },
  {
    id: 'USR-8932',
    name: 'Zara Nielsen',
    email: 'zara@nordicinteriors.dk',
    handle: 'zaranielsen',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    role: 'creator',
    status: 'active',
    category: 'Scandinavian Living & Design',
    location: 'Copenhagen, Denmark',
    rating: 4.96,
    totalVolumeEur: 35100,
    ordersCount: 30,
    joinedDate: '2024-02-08',
  },
  {
    id: 'USR-8933',
    name: 'NovaTech Audio',
    email: 'partners@novatech-audio.kr',
    handle: 'novatechaudio',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
    role: 'brand',
    status: 'active',
    companyName: 'NovaTech Sound Innovations Co.',
    location: 'Seoul, South Korea',
    totalVolumeEur: 76200,
    ordersCount: 21,
    joinedDate: '2024-01-12',
  },
];

export const INITIAL_VERIFICATIONS: VerificationRequest[] = [
  {
    id: 'VRF-401',
    creatorId: 'USR-9001',
    creatorName: 'Aria Montclaire',
    email: 'aria@montclaire.studio',
    handle: 'ariamontclaire',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    category: 'Fashion',
    platform: 'Instagram',
    submittedDate: '2026-09-26',
    status: 'pending',
  },
  {
    id: 'VRF-402',
    creatorId: 'USR-9002',
    creatorName: 'Kaito Tanaka',
    email: 'kaito@tanaka-ugc.jp',
    handle: 'kaitotanaka',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    category: 'Culinary',
    platform: 'YouTube',
    submittedDate: '2026-09-25',
    status: 'pending',
  },
  {
    id: 'VRF-403',
    creatorId: 'USR-8911',
    creatorName: 'Sophie Kim',
    email: 'sophie@sophiekim.com',
    handle: 'sophiekim',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    category: 'Beauty',
    platform: 'TikTok',
    submittedDate: '2026-09-20',
    status: 'approved',
  },
];

export const INITIAL_DISPUTES: EscrowDispute[] = [
  {
    id: 'DSP-8821',
    orderId: 'ORD-94102',
    brandName: 'Aura Skincare Paris',
    brandAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    creatorName: 'Sophie Kim',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    campaignTitle: 'Serum Launch 4K UGC Reel + 2 Re-cuts',
    amountEur: 1200,
    feeEur: 180,
    disputeReason: 'Brand claims lighting & tone do not match agreed moodboard; Creator claims script was fully approved.',
    status: 'open',
    submittedDate: '2026-09-24',
    briefSummary: 'Deliver 1x 45s vertical reel featuring hydrating serum texture shot and 3-second hook.',
    deliverableLink: 'https://storage.influverse.com/deliverables/nordica_draft_v2.mp4',
  },
];

export const INITIAL_LEGAL_DOCS: CmsLegalDoc[] = [
  {
    id: 'CMS-TOS',
    slug: 'terms',
    title: 'Terms of Service',
    version: '1.0',
    lastModified: 'September 2026',
    isPublished: true,
    contentMarkdown: `# Terms of Service — Influverse Marketplace

## 1. Introduction and Acceptance
By registering as a Brand or Creator on Influverse, you accept full adherence to these terms, our 15% escrow policy, and our dispute arbitration procedures.

## 2. Escrow Protection & Platform Fee (15%)
Influverse operates a non-custodial milestone escrow mechanism for all campaign agreements. When a Brand funds a collaboration, the total contract amount plus a transparent 15% marketplace platform fee is authorized and funded into secure escrow.

## 3. Creator Obligations & Deliverables
Creators agree to produce and submit original, high-fidelity content adhering strictly to the campaign brief, guidelines, and agreed delivery dates. Unless specified otherwise, creators provide up to 2 revisions.

## 4. Brand Usage Rights & Licensing
Upon release of escrow funds, the Brand receives commercial licensing rights defined in the purchased Creator package (e.g. 30-day, 90-day, or perpetual paid ad usage).

## 5. Dispute Resolution & Mediation
In the event of a disagreement regarding deliverable compliance, either party may request Influverse mediation. Our trust team reviews the brief and deliverables to render an impartial determination.`,
  },
  {
    id: 'CMS-PRIVACY',
    slug: 'privacy',
    title: 'Privacy Policy',
    version: '1.0',
    lastModified: 'September 2026',
    isPublished: true,
    contentMarkdown: `# Privacy Policy & GDPR Compliance

## 1. Information We Collect
We collect personal identification, business legal registration, social media statistics, and billing information necessary to execute contracts and deliver tax-compliant invoices.

## 2. Social API Data & Analytics
When creators authenticate their social accounts (Instagram, TikTok, YouTube), we receive read-only public profile metrics, follower counts, and engagement percentages. We never ask for or store passwords.

## 3. Payment Processing & Escrow Security
All payment processing is handled via PCI-DSS Level 1 compliant financial payment gateways (Stripe & Wise). We do not store raw credit card numbers.

## 4. GDPR & Your Privacy Rights
Under the EU GDPR, users have full rights to access, rectify, port, or request deletion of their personal data. Requests can be submitted anytime via privacy@influverse.com.`,
  },
  {
    id: 'CMS-ABOUT',
    slug: 'about',
    title: 'About Us',
    version: '1.0',
    lastModified: 'September 2026',
    isPublished: true,
    contentMarkdown: `# About Influverse — The Premier Creator Marketplace

## Good Work Starts With The Right Connection
Influverse connects forward-thinking brands with verified content creators worldwide for sponsored collaborations and bespoke UGC. We bring creator discovery, clear offers, and content delivery into one place.

## Why We Built Influverse
Finding the right collaborator should feel simple. Influverse eliminates back-and-forth negotiations, opaque pricing, and payment uncertainty with automated milestone escrows and verified creator analytics.

## Core Guarantees
- 100% Escrow Protection on every collaboration
- Direct SEPA & SWIFT creator payouts within 48 hours
- Transparent 15% marketplace take-rate with no hidden deductions
- Verified engagement metrics directly audited from social APIs`,
  },
];

export const INITIAL_FAQS: CmsFaqItem[] = [
  {
    id: 'FAQ-01',
    category: 'brands',
    question: 'How does the Influverse escrow system protect my budget?',
    answer: 'When a brand sends an offer, the campaign budget (creator rate + 15% platform fee) is placed into a secure escrow account. The creator starts working with complete confidence that funds are secured. Funds are only transferred to the creator once you review and approve the submitted content.',
    order: 1,
    isPublished: true,
  },
  {
    id: 'FAQ-02',
    category: 'general',
    question: 'Why is Influverse different from traditional influencer agencies?',
    answer: 'Influverse eliminates middleman markups, slow email chains, and opaque pricing. Brands get direct access to verified creator rate cards, 100% escrow milestone protection, on-demand portfolio previews, and automated EU VAT invoicing.',
    order: 2,
    isPublished: true,
  },
  {
    id: 'FAQ-03',
    category: 'creators',
    question: 'Do creators have to pay any fee or commission?',
    answer: 'No. Creators keep 100% of their listed package price. The 15% platform fee is covered by the hiring brand to fund escrow protection, contract guarantees, dispute mediation, and secure instant payouts.',
    order: 3,
    isPublished: true,
  },
  {
    id: 'FAQ-04',
    category: 'brands',
    question: 'What is the difference between UGC Content and a Sponsored Post?',
    answer: 'UGC (User Generated Content) is custom high-converting photo/video assets produced by the creator for your brand to run on your own official channels or paid ad campaigns. A Sponsored Post includes the creator publishing the content directly to their own engaged audience on Instagram, TikTok, or YouTube.',
    order: 4,
    isPublished: true,
  },
  {
    id: 'FAQ-05',
    category: 'general',
    question: 'How do revisions work if I need changes on the content?',
    answer: 'Each creator package includes specified revision rounds (typically 1 to 2 revisions). When a creator submits draft deliverables, you can request adjustments directly inside your order workspace with timestamped notes before final escrow sign-off.',
    order: 5,
    isPublished: true,
  },
  {
    id: 'FAQ-06',
    category: 'creators',
    question: 'Are all creators verified on Influverse?',
    answer: 'Yes. Our talent team manually verifies creator identity, authentic audience engagement metrics, past brand collaborations, and channel handles across Instagram, TikTok, and YouTube before granting the verified checkmark badge.',
    order: 6,
    isPublished: true,
  },
  {
    id: 'FAQ-07',
    category: 'escrow',
    question: 'What currencies and payment methods are supported?',
    answer: 'All packages, custom offers, and balance transactions are standardized in EUR (€) with support for major credit cards (Visa, Mastercard, Amex), SEPA bank transfers, Apple Pay, and Google Pay.',
    order: 7,
    isPublished: true,
  },
];

export const INITIAL_BRAND_ASSETS: CmsBrandAssets = {
  logoLightUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&q=80',
  logoDarkUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&q=80',
  faviconUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=32&q=80',
  heroHeadline: 'Where Luxury Brands Discover & Hire Top 1% Creators',
  heroSubtitle: 'The high-trust creator marketplace with 100% escrow protection and direct EUR pricing.',
  supportEmail: 'concierge@influverse.com',
  socialLinks: {
    instagram: 'https://instagram.com/influverse',
    twitter: 'https://twitter.com/influverse',
    linkedin: 'https://linkedin.com/company/influverse',
  },
};

export const INITIAL_TRANSACTIONS: MarketplaceTransaction[] = [
  {
    id: 'TXN-90241',
    orderId: 'ORD-94102',
    brandName: 'Aura Skincare Paris',
    brandAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    creatorName: 'Sophie Kim',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    campaignTitle: 'Serum Launch 4K UGC Reel + 2 Re-cuts',
    type: 'escrow_deposit',
    grossAmountEur: 1380,
    platformFeeEur: 180,
    netAmountEur: 1200,
    paymentMethod: 'stripe_connect',
    status: 'escrow_locked',
    createdAt: '2026-09-24 14:22:10',
    stripePaymentIntentId: 'pi_3P92k8Lkd0192InfluverseAura',
    invoiceNumber: 'INV-2026-09-081',
  },
  {
    id: 'TXN-90240',
    orderId: 'ORD-93988',
    brandName: 'Nordica Activewear',
    brandAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    creatorName: 'Maya Chen',
    creatorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    campaignTitle: 'Autumn Seamless Leggings UGC Bundle',
    type: 'creator_payout',
    grossAmountEur: 2875,
    platformFeeEur: 375,
    netAmountEur: 2500,
    paymentMethod: 'wise',
    status: 'completed',
    createdAt: '2026-09-23 11:05:40',
    stripePaymentIntentId: 'tr_1N89xLkd0219NordicaMaya',
    invoiceNumber: 'INV-2026-09-079',
  },
  {
    id: 'TXN-90239',
    orderId: 'ORD-93988',
    brandName: 'Nordica Activewear',
    brandAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    creatorName: 'Maya Chen',
    creatorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    campaignTitle: 'Autumn Seamless Leggings UGC Bundle',
    type: 'platform_fee',
    grossAmountEur: 375,
    platformFeeEur: 375,
    netAmountEur: 375,
    paymentMethod: 'stripe_connect',
    status: 'completed',
    createdAt: '2026-09-23 11:05:42',
    stripePaymentIntentId: 'fee_9x0182InfluverseCommission',
    invoiceNumber: 'INV-2026-09-080',
  },
  {
    id: 'TXN-90238',
    orderId: 'ORD-93810',
    brandName: 'Veloce Geneva Horology',
    brandAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    creatorName: 'Liam Carter',
    creatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    campaignTitle: 'Chronograph Macro Video Reel (4K RAW)',
    type: 'creator_payout',
    grossAmountEur: 4600,
    platformFeeEur: 600,
    netAmountEur: 4000,
    paymentMethod: 'sepa_transfer',
    status: 'completed',
    createdAt: '2026-09-21 09:30:15',
    stripePaymentIntentId: 'tr_4K0188VeloceCarterPayout',
    invoiceNumber: 'INV-2026-09-074',
  },
  {
    id: 'TXN-90237',
    orderId: 'ORD-93701',
    brandName: 'Soleil Botanicals',
    brandAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    creatorName: 'Darius Vance',
    creatorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    campaignTitle: 'Summer Glow Mist TikTok Spark Ad',
    type: 'brand_refund',
    grossAmountEur: 1150,
    platformFeeEur: 150,
    netAmountEur: 1150,
    paymentMethod: 'credit_card',
    status: 'refunded',
    createdAt: '2026-09-18 16:45:00',
    stripePaymentIntentId: 're_1N0928RefundSoleilVance',
    invoiceNumber: 'REF-2026-09-012',
  },
  {
    id: 'TXN-90236',
    orderId: 'ORD-93655',
    brandName: 'Maison Lumiere Paris',
    brandAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    creatorName: 'Sophie Kim',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    campaignTitle: 'Silk Scarf Editorial Carousel + Storyboard',
    type: 'escrow_deposit',
    grossAmountEur: 2300,
    platformFeeEur: 300,
    netAmountEur: 2000,
    paymentMethod: 'stripe_connect',
    status: 'escrow_locked',
    createdAt: '2026-09-17 10:12:00',
    stripePaymentIntentId: 'pi_8K1029LumiereKimDeposit',
    invoiceNumber: 'INV-2026-09-068',
  },
];

export const INITIAL_PACKAGES: MarketplacePackage[] = [
  {
    id: 'PKG-101',
    title: 'Hero 4K TikTok / Reel UGC Showcase',
    description: 'High-energy organic hook, unboxing & product demonstration filmed in 4K with color grading.',
    category: 'Beauty & Skincare',
    tier: 'standard',
    priceEur: 850,
    deliveryDays: 5,
    revisionsCount: 2,
    adRightsMonths: 12,
    deliverables: [
      '1x 45s Vertical Video (9:16 4K)',
      '2x Hook Variations for A/B Testing',
      'Script Approval Before Filming',
      'Raw Footage & Audio Stems',
    ],
    isFeatured: true,
    isPublished: true,
    ordersCount: 48,
    creatorCount: 142,
    createdAt: '2026-01-15',
  },
  {
    id: 'PKG-102',
    title: 'High-Converting TikTok Spark Ad Bundle',
    description: 'Built specifically for paid digital ads with 3 hook variations and call-to-action overlays.',
    category: 'Fashion & Apparel',
    tier: 'premium',
    priceEur: 1600,
    deliveryDays: 7,
    revisionsCount: 3,
    adRightsMonths: 24,
    deliverables: [
      '2x Finished 30-45s Creative Reels',
      '3x Alternate 3-Second Hooks',
      'Spark Ads Whitelisting Authorization Code',
      'Captions & On-Screen Dynamic Text',
    ],
    isFeatured: true,
    isPublished: true,
    ordersCount: 32,
    creatorCount: 88,
    createdAt: '2026-02-01',
  },
  {
    id: 'PKG-103',
    title: 'Organic Lifestyle Integration Video',
    description: 'Casual, native seamless product placement integrated naturally into day-in-the-life vlog content.',
    category: 'Wellness & Fitness',
    tier: 'starter',
    priceEur: 450,
    deliveryDays: 4,
    revisionsCount: 1,
    adRightsMonths: 6,
    deliverables: [
      '1x 60s Vlog Integration',
      'Native Story Posting on IG with Link Sticker',
      'Organic Brand Tag & Hashtag Strategy',
    ],
    isFeatured: false,
    isPublished: true,
    ordersCount: 65,
    creatorCount: 210,
    createdAt: '2026-02-20',
  },
  {
    id: 'PKG-104',
    title: 'Enterprise Multi-Creator Campaign Pack',
    description: 'Curated squadron of 5 verified creators delivering cross-platform coverage and ad whitelisting.',
    category: 'Tech & Gadgets',
    tier: 'enterprise',
    priceEur: 4800,
    deliveryDays: 14,
    revisionsCount: 3,
    adRightsMonths: 24,
    deliverables: [
      '5x Distinct Creator Deliverables',
      'Complete Raw B-Roll Asset Library',
      'Full Paid Ads Whitelisting Rights (24 Mo)',
      'Dedicated Influverse Campaign Supervisor',
    ],
    isFeatured: true,
    isPublished: true,
    ordersCount: 12,
    creatorCount: 28,
    createdAt: '2026-03-10',
  },
];

export const INITIAL_ORDERS: MarketplaceOrder[] = [
  {
    id: 'ORD-89421',
    packageTitle: '3x High-Converting TikTok UGC Videos',
    packageTier: 'standard',
    category: 'Beauty & Skincare',
    brandName: 'Nordica Botanicals',
    brandAvatar: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=400&q=80',
    brandEmail: 'partnerships@nordicabotanicals.com',
    creatorName: 'Elena Rostova',
    creatorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    creatorHandle: '@elena_ugc',
    grossAmountEur: 1200,
    platformFeeEur: 180,
    creatorNetEur: 1020,
    status: 'deliverable_submitted',
    progressPercent: 75,
    deliveryDaysTotal: 5,
    daysRemaining: 1,
    dueDate: '2026-09-29',
    revisionCurrent: 0,
    revisionMax: 2,
    deliverablesSummary: [
      '1x 45s Hook Video (4K 60fps)',
      '2x Hook Variations for A/B Testing',
      '12 Months Commercial Whitelisting Rights',
    ],
    deliverableLink: 'https://storage.influverse.com/assets/nordica_v1_final.mp4',
    escrowDepositId: 'ESC-89421-DEP',
    milestones: [
      { title: 'Escrow Deposit Funded by Brand (€1,200 Secured)', status: 'completed', timestamp: 'Sep 24, 10:14 AM' },
      { title: 'Creative Script & Shotlist Pre-Approved', status: 'completed', timestamp: 'Sep 25, 03:30 PM' },
      { title: 'Final 4K Video Assets Produced & Uploaded', status: 'completed', timestamp: 'Sep 27, 08:20 PM' },
      { title: 'Brand Review & QA Sign-Off (Auto-disburse in 36h)', status: 'current', timestamp: 'Active Now' },
      { title: 'Escrow Payout Disbursed to Creator (€1,020)', status: 'pending' },
    ],
    createdAt: '2026-09-24',
    lastActivity: '12 minutes ago',
    brandNotes: 'Please ensure that the product serum dropper shot is crisp and brand label is visible at 0:03.',
    slaWarning: false,
  },
  {
    id: 'ORD-89418',
    packageTitle: 'High-Converting TikTok Spark Ad Bundle',
    packageTier: 'premium',
    category: 'Fashion & Apparel',
    brandName: 'Verve Apparel Munich',
    brandAvatar: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=400&q=80',
    brandEmail: 'growth@vervemunich.de',
    creatorName: 'Marcus Vance',
    creatorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    creatorHandle: '@marcus_vance',
    grossAmountEur: 1600,
    platformFeeEur: 240,
    creatorNetEur: 1360,
    status: 'revision_requested',
    progressPercent: 60,
    deliveryDaysTotal: 7,
    daysRemaining: 2,
    dueDate: '2026-09-30',
    revisionCurrent: 1,
    revisionMax: 3,
    deliverablesSummary: [
      '2x Finished 30-45s Creative Reels',
      '3x Alternate 3-Second Hooks',
      'Spark Ads Whitelisting Authorization Code',
    ],
    deliverableLink: 'https://storage.influverse.com/assets/verve_autumn_drop_r1.mp4',
    escrowDepositId: 'ESC-89418-DEP',
    milestones: [
      { title: 'Escrow Deposit Funded (€1,600 in Vault)', status: 'completed', timestamp: 'Sep 22, 11:00 AM' },
      { title: 'Script Outline & Moodboard Approved', status: 'completed', timestamp: 'Sep 23, 02:15 PM' },
      { title: 'First Production Draft Submitted', status: 'completed', timestamp: 'Sep 26, 06:40 PM' },
      { title: 'Revision Round 1 Requested by Brand', status: 'current', timestamp: 'Sep 27, 09:30 AM', notes: 'Shorten opening hook cut by 0.5s and rebalance vocal mix.' },
      { title: 'Brand Sign-Off & Escrow Release', status: 'pending' },
    ],
    createdAt: '2026-09-22',
    lastActivity: '2 hours ago',
    brandNotes: 'Need the hook jump-cut tightened by 0.5s and background track swapped with royalty-free alternative.',
    slaWarning: false,
  },
  {
    id: 'ORD-89412',
    packageTitle: 'Organic Lifestyle Integration Video',
    packageTier: 'starter',
    category: 'Wellness & Fitness',
    brandName: 'Kura Supplements',
    brandAvatar: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=400&q=80',
    brandEmail: 'hello@kurasupplements.com',
    creatorName: 'Zoe Chen',
    creatorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    creatorHandle: '@zoe_fitlife',
    grossAmountEur: 450,
    platformFeeEur: 67.5,
    creatorNetEur: 382.5,
    status: 'in_progress',
    progressPercent: 40,
    deliveryDaysTotal: 4,
    daysRemaining: 2,
    dueDate: '2026-09-30',
    revisionCurrent: 0,
    revisionMax: 1,
    deliverablesSummary: [
      '1x 60s Native Gym Vlog Integration',
      'Native Story Posting on Instagram with Sticker Link',
      'Organic Brand Tag & Hashtag Strategy',
    ],
    escrowDepositId: 'ESC-89412-DEP',
    milestones: [
      { title: 'Escrow Deposit Funded (€450 Secured)', status: 'completed', timestamp: 'Sep 26, 04:00 PM' },
      { title: 'Script & Product Placement Outline Approved', status: 'completed', timestamp: 'Sep 27, 11:20 AM' },
      { title: 'Production Filming in Gym / Daily Routine', status: 'current', timestamp: 'In Production' },
      { title: 'Deliverable Review & Approval', status: 'pending' },
      { title: 'Escrow Disbursement to Creator', status: 'pending' },
    ],
    createdAt: '2026-09-26',
    lastActivity: '4 hours ago',
    brandNotes: 'Emphasize natural morning energy without jitters.',
    slaWarning: false,
  },
  {
    id: 'ORD-89399',
    packageTitle: 'Enterprise Multi-Creator Campaign Pack',
    packageTier: 'enterprise',
    category: 'Tech & Gadgets',
    brandName: 'Lumina Smart Home',
    brandAvatar: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&w=400&q=80',
    brandEmail: 'campaigns@luminahome.io',
    creatorName: 'Lucas Meyer',
    creatorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    creatorHandle: '@lucasmeyer_tech',
    grossAmountEur: 4800,
    platformFeeEur: 720,
    creatorNetEur: 4080,
    status: 'in_progress',
    progressPercent: 35,
    deliveryDaysTotal: 14,
    daysRemaining: -1,
    dueDate: '2026-09-27',
    revisionCurrent: 0,
    revisionMax: 3,
    deliverablesSummary: [
      '5x Distinct Creator Deliverables across YouTube & TikTok',
      'Complete Raw B-Roll Asset Library (4K ProRes)',
      'Full Paid Ads Whitelisting Rights (24 Months)',
      'Dedicated Influverse Campaign Supervisor',
    ],
    escrowDepositId: 'ESC-89399-DEP',
    milestones: [
      { title: 'Escrow Deposit Funded (€4,800 Vault Hold)', status: 'completed', timestamp: 'Sep 13, 09:30 AM' },
      { title: 'Hardware Shipment & Pre-Production Brief', status: 'completed', timestamp: 'Sep 16, 02:00 PM' },
      { title: 'Studio Production & Smart Hub Demo', status: 'current', timestamp: '⚠️ 1 Day Overdue SLA', notes: 'Creator reported 48h customs hold on EU test unit' },
      { title: 'Deliverable Review & Raw Media Kit Transfer', status: 'pending' },
      { title: 'Escrow Milestone Release (€4,080)', status: 'pending' },
    ],
    createdAt: '2026-09-13',
    lastActivity: 'Yesterday',
    brandNotes: 'Physical demo unit arrived on Sep 18; Creator requested a 48h extension due to customs delay.',
    slaWarning: true,
  },
  {
    id: 'ORD-89380',
    packageTitle: 'Brand Ambassador Quarterly Pilot',
    packageTier: 'enterprise',
    category: 'Luxury Lifestyle',
    brandName: 'Atelier Mode Geneva',
    brandAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
    brandEmail: 'vip@ateliermode.ch',
    creatorName: 'Chloe Laurent',
    creatorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    creatorHandle: '@chloe_styleparis',
    grossAmountEur: 3200,
    platformFeeEur: 480,
    creatorNetEur: 2720,
    status: 'escrow_funded',
    progressPercent: 15,
    deliveryDaysTotal: 10,
    daysRemaining: 9,
    dueDate: '2026-10-07',
    revisionCurrent: 0,
    revisionMax: 2,
    deliverablesSummary: [
      '3x High-Fashion Editorial Video Lookbooks',
      'Raw High-Resolution Asset Stems',
      'Full Worldwide Digital Commercial Rights',
    ],
    escrowDepositId: 'ESC-89380-DEP',
    milestones: [
      { title: 'Escrow Deposit Funded (€3,200 Vault Hold)', status: 'completed', timestamp: 'Today, 08:30 AM' },
      { title: 'Script Outline & Moodboard Approval', status: 'current', timestamp: 'Awaiting Brand Approval' },
      { title: 'Paris Studio Production Session', status: 'pending' },
      { title: 'Asset Review & Whitelisting Setup', status: 'pending' },
      { title: 'Escrow Payout Disbursed to Creator', status: 'pending' },
    ],
    createdAt: '2026-09-28',
    lastActivity: '30 minutes ago',
    brandNotes: 'Shoot against neutral Haussmann apartment interior backdrop.',
    slaWarning: false,
  },
  {
    id: 'ORD-89365',
    packageTitle: 'Viral TikTok Sound & Product Sync',
    packageTier: 'standard',
    category: 'Consumer Apps',
    brandName: 'FocusFlow App',
    brandAvatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=400&q=80',
    brandEmail: 'acquisition@focusflow.co',
    creatorName: 'Mia Althaus',
    creatorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    creatorHandle: '@mia_productivity',
    grossAmountEur: 950,
    platformFeeEur: 142.5,
    creatorNetEur: 807.5,
    status: 'completed',
    progressPercent: 100,
    deliveryDaysTotal: 5,
    daysRemaining: 0,
    dueDate: '2026-09-25',
    revisionCurrent: 1,
    revisionMax: 2,
    deliverablesSummary: [
      '1x 45s High-Conversion Product Demo',
      'Trending Audio Synchronization',
      'Pinned Comment with Direct Store Link',
    ],
    deliverableLink: 'https://storage.influverse.com/assets/focusflow_approved_v2.mp4',
    escrowDepositId: 'ESC-89365-DEP',
    milestones: [
      { title: 'Escrow Deposit Funded (€950 Secured)', status: 'completed', timestamp: 'Sep 20, 10:00 AM' },
      { title: 'Script Approved', status: 'completed', timestamp: 'Sep 21, 01:20 PM' },
      { title: 'Video Uploaded & Whitelisted', status: 'completed', timestamp: 'Sep 23, 05:40 PM' },
      { title: 'Brand 5-Star Approval & Review', status: 'completed', timestamp: 'Sep 25, 11:15 AM' },
      { title: 'Escrow Released to Creator €807.50', status: 'completed', timestamp: 'Sep 25, 11:16 AM' },
    ],
    createdAt: '2026-09-20',
    lastActivity: 'Sep 25',
    brandNotes: 'Exceptional CTR on Day 1 of Spark Ads deployment.',
    slaWarning: false,
  },
];

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: 'TCK-501',
    type: 'user_report',
    subject: 'Report: Suspected bot engagement / fake views on creator profile',
    category: 'fraud_scam',
    userName: 'Nordica Botanicals',
    userEmail: 'partnerships@nordicabotanicals.com',
    userRole: 'brand',
    userAvatar: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=400&q=80',
    priority: 'urgent',
    status: 'open',
    reportedUser: {
      name: 'FakeGrowth Studio',
      handle: '@bot_creator',
      role: 'creator',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=400&q=80',
      reason: 'Sudden spike of 50k views within 10 minutes with 0 comments.',
    },
    messages: [
      {
        id: 'MSG-01',
        senderName: 'Nordica Botanicals',
        senderRole: 'brand',
        senderAvatar: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=400&q=80',
        message: 'We funded an order with this creator yesterday and noticed their TikTok video comments are all copy-paste bot accounts. Please investigate their engagement before escrow funds are released.',
        timestamp: 'Today at 08:30 AM',
      },
    ],
    createdAt: '2026-09-28',
    lastUpdated: '10 minutes ago',
  },
  {
    id: 'TCK-502',
    type: 'support',
    subject: 'SEPA Escrow Deposit verification confirmation delay',
    category: 'billing_escrow',
    userName: 'Aura Skincare Paris',
    userEmail: 'marketing@auraskincare.fr',
    userRole: 'brand',
    userAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    priority: 'high',
    status: 'in_progress',
    assignedAdmin: 'Sazzad Hoshen',
    messages: [
      {
        id: 'MSG-02',
        senderName: 'Aura Skincare Paris',
        senderRole: 'brand',
        senderAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
        message: 'We initiated a SEPA wire transfer of €3,400 for our autumn launch 2 days ago. Our bank confirmed it cleared, but the dashboard still shows "Pending Bank Clearing".',
        timestamp: 'Sep 27, 02:15 PM',
      },
      {
        id: 'MSG-03',
        senderName: 'Sazzad Hoshen (Super Admin)',
        senderRole: 'admin',
        senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
        message: 'Hello Aura team. Our banking partner Stripe SEPA Treasury processes clearing within 1-2 business days. We have escalated this to our settlement team for manual reconciliation.',
        timestamp: 'Sep 27, 03:45 PM',
        isAdminReply: true,
      },
    ],
    createdAt: '2026-09-27',
    lastUpdated: '1 hour ago',
  },
  {
    id: 'TCK-503',
    type: 'user_report',
    subject: 'Brand demanding 4th revision without paying add-on fee',
    category: 'order_delivery',
    userName: 'Elena Rostova',
    userEmail: 'elena.rostova@creator.com',
    userRole: 'creator',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    priority: 'high',
    status: 'open',
    reportedUser: {
      name: 'Verve Apparel Munich',
      role: 'brand',
      avatar: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=400&q=80',
      reason: 'Brand insisting on completely re-shooting after 2 agreed revisions exhausted.',
    },
    messages: [
      {
        id: 'MSG-04',
        senderName: 'Elena Rostova',
        senderRole: 'creator',
        senderAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
        message: 'The contract for Order #ORD-89418 included 2 revisions. I already provided both edits based on their written notes. Now the brand wants me to re-film with a new outfit and refused to release escrow.',
        timestamp: 'Today at 09:10 AM',
      },
    ],
    createdAt: '2026-09-28',
    lastUpdated: '35 minutes ago',
  },
  {
    id: 'TCK-504',
    type: 'support',
    subject: 'Request to update registered EU VAT ID for corporate invoicing',
    category: 'billing_escrow',
    userName: 'Kura Supplements',
    userEmail: 'billing@kurasupplements.com',
    userRole: 'brand',
    userAvatar: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=400&q=80',
    priority: 'normal',
    status: 'resolved',
    assignedAdmin: 'Sazzad Hoshen',
    messages: [
      {
        id: 'MSG-05',
        senderName: 'Kura Supplements',
        senderRole: 'brand',
        senderAvatar: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=400&q=80',
        message: 'We recently restructured our EU holding entity. We need our VAT number updated on our marketplace invoices from DE384920 to DE992817.',
        timestamp: 'Sep 25, 11:00 AM',
      },
      {
        id: 'MSG-06',
        senderName: 'Sazzad Hoshen (Super Admin)',
        senderRole: 'admin',
        senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
        message: 'Done! We have verified your new VAT registration with VIES database and updated your billing profile. All upcoming invoice PDFs will reflect DE992817.',
        timestamp: 'Sep 25, 12:30 PM',
        isAdminReply: true,
      },
    ],
    createdAt: '2026-09-25',
    lastUpdated: 'Sep 25',
  },
  {
    id: 'TCK-505',
    type: 'user_report',
    subject: 'Brand running whitelisted ad past the 6-month contract license',
    category: 'copyright_ip',
    userName: 'Marcus Vance',
    userEmail: 'marcus.vance@creator.com',
    userRole: 'creator',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    priority: 'urgent',
    status: 'in_progress',
    reportedUser: {
      name: 'Urban Streetwear UK',
      role: 'brand',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
      reason: 'Using my face on Meta Ads after license expiration.',
    },
    messages: [
      {
        id: 'MSG-07',
        senderName: 'Marcus Vance',
        senderRole: 'creator',
        senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
        message: 'I booked a 6-month UGC package in February 2026 with Urban Streetwear. My license expired August 31. They are still actively running my video on Facebook Ads Library with €10k+ spend.',
        timestamp: 'Sep 26, 04:00 PM',
      },
      {
        id: 'MSG-08',
        senderName: 'Sazzad Hoshen (Super Admin)',
        senderRole: 'admin',
        senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
        message: 'We have reviewed the Meta Ad Library link and issued a formal cease-and-desist demand to the brands legal contact. Their account has been temporarily restricted until paid renewal is settled.',
        timestamp: 'Sep 26, 05:20 PM',
        isAdminReply: true,
      },
    ],
    createdAt: '2026-09-26',
    lastUpdated: 'Yesterday',
  },
];




